language: python
python: "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov pytest pytest-cov
script:
  - pytest --cov=./
after_success:
  - codecov
